-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
-- Version: 2021.2
-- Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity filter3x3_orig_convolution_int_3_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    image_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    image_r_TVALID : IN STD_LOGIC;
    image_r_TREADY : OUT STD_LOGIC;
    output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC );
end;


architecture behav of filter3x3_orig_convolution_int_3_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    signal image_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln18_fu_357_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal icmp_ln28_reg_899 : STD_LOGIC_VECTOR (0 downto 0);
    signal window_buffer_10_reg_825 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_12_reg_832 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_14_reg_839 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_16_reg_847 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_18_reg_855 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_20_reg_863 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_22_reg_871 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_24_reg_878 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_2_fu_363_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_2_reg_888 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_reg_893 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln28_fu_379_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_9_reg_903 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_10_reg_909 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_load_1_reg_915 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_11_reg_920 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_6_load_1_reg_926 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_12_reg_931 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_8_load_1_reg_937 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_13_reg_942 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_10_load_1_reg_948 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_14_reg_953 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal i_fu_76 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_state9 : BOOLEAN;
    signal ap_block_state9_io : BOOLEAN;
    signal sum_1_fu_80 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_2_fu_84 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_4_fu_88 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_6_fu_92 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_8_fu_96 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_10_fu_100 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_fu_104 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_2_fu_108 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_1_fu_112 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_3_fu_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_4_fu_120 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_5_fu_124 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_6_fu_128 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_7_fu_132 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_8_fu_136 : STD_LOGIC_VECTOR (31 downto 0);
    signal window_buffer_9_fu_140 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state4 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_block_state5 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_block_state6 : BOOLEAN;
    signal ap_block_state6_io : BOOLEAN;
    signal ap_block_state7 : BOOLEAN;
    signal ap_block_state7_io : BOOLEAN;
    signal ap_block_state8 : BOOLEAN;
    signal ap_block_state8_io : BOOLEAN;
    signal sum_fu_406_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_12_fu_434_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_13_fu_461_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_14_fu_488_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_15_fu_515_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_16_fu_542_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_8_fu_369_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal add_ln65_fu_385_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_2_fu_396_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_3_fu_401_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_1_fu_391_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_5_fu_413_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_7_fu_424_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_8_fu_429_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_6_fu_419_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_10_fu_441_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_12_fu_452_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_13_fu_456_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_11_fu_447_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_15_fu_468_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_17_fu_479_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_18_fu_483_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_16_fu_474_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_20_fu_495_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_22_fu_506_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_23_fu_510_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_21_fu_501_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_25_fu_522_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_27_fu_533_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_28_fu_537_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln65_26_fu_528_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_condition_515 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_fu_76 <= ap_const_lv4_0;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                i_fu_76 <= i_2_reg_888;
            end if; 
        end if;
    end process;

    sum_10_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sum_10_fu_100 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_5;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                sum_10_fu_100 <= window_buffer_20_reg_863;
            end if; 
        end if;
    end process;

    sum_1_fu_80_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sum_1_fu_80 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                sum_1_fu_80 <= window_buffer_10_reg_825;
            end if; 
        end if;
    end process;

    sum_2_fu_84_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sum_2_fu_84 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_1;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                sum_2_fu_84 <= window_buffer_12_reg_832;
            end if; 
        end if;
    end process;

    sum_4_fu_88_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sum_4_fu_88 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_2;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                sum_4_fu_88 <= window_buffer_14_reg_839;
            end if; 
        end if;
    end process;

    sum_6_fu_92_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sum_6_fu_92 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_3;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                sum_6_fu_92 <= window_buffer_16_reg_847;
            end if; 
        end if;
    end process;

    sum_8_fu_96_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                sum_8_fu_96 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_4;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                sum_8_fu_96 <= window_buffer_18_reg_855;
            end if; 
        end if;
    end process;

    window_buffer_1_fu_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_1_fu_112 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_1_fu_112 <= tmp_reg_893;
            end if; 
        end if;
    end process;

    window_buffer_2_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_2_fu_108 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_7;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_2_fu_108 <= window_buffer_24_reg_878;
            end if; 
        end if;
    end process;

    window_buffer_3_fu_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_3_fu_116 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_1;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_3_fu_116 <= tmp_9_reg_903;
            end if; 
        end if;
    end process;

    window_buffer_4_fu_120_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_4_fu_120 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_2;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_4_fu_120 <= tmp_10_reg_909;
            end if; 
        end if;
    end process;

    window_buffer_5_fu_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_5_fu_124 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_3;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_5_fu_124 <= tmp_11_reg_920;
            end if; 
        end if;
    end process;

    window_buffer_6_fu_128_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_6_fu_128 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_4;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_6_fu_128 <= tmp_12_reg_931;
            end if; 
        end if;
    end process;

    window_buffer_7_fu_132_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_7_fu_132 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_5;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_7_fu_132 <= tmp_13_reg_942;
            end if; 
        end if;
    end process;

    window_buffer_8_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_8_fu_136 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_6;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_8_fu_136 <= tmp_14_reg_953;
            end if; 
        end if;
    end process;

    window_buffer_9_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_9_fu_140 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_7;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_9_fu_140 <= image_r_TDATA;
            end if; 
        end if;
    end process;

    window_buffer_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                window_buffer_fu_104 <= void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_6;
            elsif ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                window_buffer_fu_104 <= window_buffer_22_reg_871;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                i_2_reg_888 <= i_2_fu_363_p2;
                window_buffer_10_reg_825 <= window_buffer_1_fu_112;
                window_buffer_12_reg_832 <= window_buffer_3_fu_116;
                window_buffer_14_reg_839 <= window_buffer_4_fu_120;
                window_buffer_16_reg_847 <= window_buffer_5_fu_124;
                window_buffer_18_reg_855 <= window_buffer_6_fu_128;
                window_buffer_20_reg_863 <= window_buffer_7_fu_132;
                window_buffer_22_reg_871 <= window_buffer_8_fu_136;
                window_buffer_24_reg_878 <= window_buffer_9_fu_140;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                icmp_ln28_reg_899 <= icmp_ln28_fu_379_p2;
                tmp_reg_893 <= image_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln28_reg_899 = ap_const_lv1_0))) then
                sum_10_load_1_reg_948 <= sum_10_fu_100;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln28_reg_899 = ap_const_lv1_0))) then
                sum_4_load_1_reg_915 <= sum_4_fu_88;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln28_reg_899 = ap_const_lv1_0))) then
                sum_6_load_1_reg_926 <= sum_6_fu_92;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln28_reg_899 = ap_const_lv1_0))) then
                sum_8_load_1_reg_937 <= sum_8_fu_96;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                tmp_10_reg_909 <= image_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                tmp_11_reg_920 <= image_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                tmp_12_reg_931 <= image_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                tmp_13_reg_942 <= image_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                tmp_14_reg_953 <= image_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                tmp_9_reg_903 <= image_r_TDATA;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state11)) then
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1 <= sum_1_fu_80;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_1 <= sum_2_fu_84;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_2 <= sum_4_fu_88;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_3 <= sum_6_fu_92;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_4 <= sum_8_fu_96;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_5 <= sum_10_fu_100;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_6 <= window_buffer_fu_104;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_1_7 <= window_buffer_2_fu_108;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2 <= window_buffer_10_reg_825;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_1 <= window_buffer_12_reg_832;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_2 <= window_buffer_14_reg_839;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_3 <= window_buffer_16_reg_847;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_4 <= window_buffer_18_reg_855;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_5 <= window_buffer_20_reg_863;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_6 <= window_buffer_22_reg_871;
                void_convolution_int_3_stream_int_0_int_const_stream_int_0_line_buffer_2_7 <= window_buffer_24_reg_878;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, image_r_TVALID, output_r_TREADY, ap_CS_fsm_state2, icmp_ln18_fu_357_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, icmp_ln28_reg_899, ap_block_state9_io, ap_block_state4_io, ap_block_state5_io, ap_block_state6_io, ap_block_state7_io, ap_block_state8_io)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (image_r_TVALID = ap_const_logic_0))) and (icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                elsif ((not(((icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (image_r_TVALID = ap_const_logic_0))) and (icmp_ln18_fu_357_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state10;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((image_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state4 => 
                if ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state4_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state5 => 
                if ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state6 => 
                if ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state7_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state8 => 
                if ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state8_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if ((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state9;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    add_ln65_10_fu_441_p2 <= std_logic_vector(unsigned(image_r_TDATA) + unsigned(sum_8_fu_96));
    add_ln65_11_fu_447_p2 <= std_logic_vector(unsigned(add_ln65_10_fu_441_p2) + unsigned(tmp_10_reg_909));
    add_ln65_12_fu_452_p2 <= std_logic_vector(unsigned(window_buffer_14_reg_839) + unsigned(sum_4_load_1_reg_915));
    add_ln65_13_fu_456_p2 <= std_logic_vector(unsigned(add_ln65_12_fu_452_p2) + unsigned(window_buffer_18_reg_855));
    add_ln65_15_fu_468_p2 <= std_logic_vector(unsigned(image_r_TDATA) + unsigned(sum_10_fu_100));
    add_ln65_16_fu_474_p2 <= std_logic_vector(unsigned(add_ln65_15_fu_468_p2) + unsigned(tmp_11_reg_920));
    add_ln65_17_fu_479_p2 <= std_logic_vector(unsigned(window_buffer_16_reg_847) + unsigned(sum_6_load_1_reg_926));
    add_ln65_18_fu_483_p2 <= std_logic_vector(unsigned(add_ln65_17_fu_479_p2) + unsigned(window_buffer_20_reg_863));
    add_ln65_1_fu_391_p2 <= std_logic_vector(unsigned(add_ln65_fu_385_p2) + unsigned(tmp_reg_893));
    add_ln65_20_fu_495_p2 <= std_logic_vector(unsigned(image_r_TDATA) + unsigned(window_buffer_fu_104));
    add_ln65_21_fu_501_p2 <= std_logic_vector(unsigned(add_ln65_20_fu_495_p2) + unsigned(tmp_12_reg_931));
    add_ln65_22_fu_506_p2 <= std_logic_vector(unsigned(window_buffer_18_reg_855) + unsigned(sum_8_load_1_reg_937));
    add_ln65_23_fu_510_p2 <= std_logic_vector(unsigned(add_ln65_22_fu_506_p2) + unsigned(window_buffer_22_reg_871));
    add_ln65_25_fu_522_p2 <= std_logic_vector(unsigned(image_r_TDATA) + unsigned(window_buffer_2_fu_108));
    add_ln65_26_fu_528_p2 <= std_logic_vector(unsigned(add_ln65_25_fu_522_p2) + unsigned(tmp_13_reg_942));
    add_ln65_27_fu_533_p2 <= std_logic_vector(unsigned(window_buffer_20_reg_863) + unsigned(sum_10_load_1_reg_948));
    add_ln65_28_fu_537_p2 <= std_logic_vector(unsigned(add_ln65_27_fu_533_p2) + unsigned(window_buffer_24_reg_878));
    add_ln65_2_fu_396_p2 <= std_logic_vector(unsigned(window_buffer_10_reg_825) + unsigned(sum_1_fu_80));
    add_ln65_3_fu_401_p2 <= std_logic_vector(unsigned(add_ln65_2_fu_396_p2) + unsigned(window_buffer_14_reg_839));
    add_ln65_5_fu_413_p2 <= std_logic_vector(unsigned(image_r_TDATA) + unsigned(sum_6_fu_92));
    add_ln65_6_fu_419_p2 <= std_logic_vector(unsigned(add_ln65_5_fu_413_p2) + unsigned(tmp_9_reg_903));
    add_ln65_7_fu_424_p2 <= std_logic_vector(unsigned(window_buffer_12_reg_832) + unsigned(sum_2_fu_84));
    add_ln65_8_fu_429_p2 <= std_logic_vector(unsigned(add_ln65_7_fu_424_p2) + unsigned(window_buffer_16_reg_847));
    add_ln65_fu_385_p2 <= std_logic_vector(unsigned(image_r_TDATA) + unsigned(sum_4_fu_88));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;
    ap_ST_fsm_state11_blk <= ap_const_logic_0;

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(image_r_TVALID, icmp_ln18_fu_357_p2)
    begin
        if (((icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (image_r_TVALID = ap_const_logic_0))) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(image_r_TVALID)
    begin
        if ((image_r_TVALID = ap_const_logic_0)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state4_blk_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899, ap_block_state4_io)
    begin
        if (((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state4_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state5_blk_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899, ap_block_state5_io)
    begin
        if (((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state6_blk_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899, ap_block_state6_io)
    begin
        if (((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state7_blk_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899, ap_block_state7_io)
    begin
        if (((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state7_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state7_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state7_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state8_blk_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899, ap_block_state8_io)
    begin
        if (((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state8_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state9_blk_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899, ap_block_state9_io)
    begin
        if (((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state9_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state9_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state2_assign_proc : process(image_r_TVALID, icmp_ln18_fu_357_p2)
    begin
                ap_block_state2 <= ((icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (image_r_TVALID = ap_const_logic_0));
    end process;


    ap_block_state4_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state4 <= ((image_r_TVALID = ap_const_logic_0) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)));
    end process;


    ap_block_state4_io_assign_proc : process(output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state4_io <= ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0));
    end process;


    ap_block_state5_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state5 <= ((image_r_TVALID = ap_const_logic_0) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)));
    end process;


    ap_block_state5_io_assign_proc : process(output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state5_io <= ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0));
    end process;


    ap_block_state6_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state6 <= ((image_r_TVALID = ap_const_logic_0) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)));
    end process;


    ap_block_state6_io_assign_proc : process(output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state6_io <= ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0));
    end process;


    ap_block_state7_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state7 <= ((image_r_TVALID = ap_const_logic_0) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)));
    end process;


    ap_block_state7_io_assign_proc : process(output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state7_io <= ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0));
    end process;


    ap_block_state8_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state8 <= ((image_r_TVALID = ap_const_logic_0) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)));
    end process;


    ap_block_state8_io_assign_proc : process(output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state8_io <= ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0));
    end process;


    ap_block_state9_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state9 <= ((image_r_TVALID = ap_const_logic_0) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)));
    end process;


    ap_block_state9_io_assign_proc : process(output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_block_state9_io <= ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0));
    end process;


    ap_condition_515_assign_proc : process(image_r_TVALID, output_r_TREADY, icmp_ln28_reg_899)
    begin
                ap_condition_515 <= (not(((image_r_TVALID = ap_const_logic_0) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (icmp_ln28_reg_899 = ap_const_lv1_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state11)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state11) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state11)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state11)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    i_2_fu_363_p2 <= std_logic_vector(unsigned(i_fu_76) + unsigned(ap_const_lv4_1));
    icmp_ln18_fu_357_p2 <= "1" when (i_fu_76 = ap_const_lv4_8) else "0";
    icmp_ln28_fu_379_p2 <= "1" when (tmp_8_fu_369_p4 = ap_const_lv3_0) else "0";

    image_r_TDATA_blk_n_assign_proc : process(image_r_TVALID, ap_CS_fsm_state2, icmp_ln18_fu_357_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state8) or (ap_const_logic_1 = ap_CS_fsm_state7) or (ap_const_logic_1 = ap_CS_fsm_state6) or (ap_const_logic_1 = ap_CS_fsm_state5) or (ap_const_logic_1 = ap_CS_fsm_state4) or (ap_const_logic_1 = ap_CS_fsm_state3) or (ap_const_logic_1 = ap_CS_fsm_state9) or ((icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            image_r_TDATA_blk_n <= image_r_TVALID;
        else 
            image_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    image_r_TREADY_assign_proc : process(image_r_TVALID, output_r_TREADY, ap_CS_fsm_state2, icmp_ln18_fu_357_p2, ap_CS_fsm_state3, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, icmp_ln28_reg_899, ap_block_state9_io, ap_block_state4_io, ap_block_state5_io, ap_block_state6_io, ap_block_state7_io, ap_block_state8_io)
    begin
        if (((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state8_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state7_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state5)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state4_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4)) or ((image_r_TVALID = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state3)) or (not(((icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (image_r_TVALID = ap_const_logic_0))) and (icmp_ln18_fu_357_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9)))) then 
            image_r_TREADY <= ap_const_logic_1;
        else 
            image_r_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    output_r_TDATA_assign_proc : process(ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, sum_fu_406_p2, sum_12_fu_434_p2, sum_13_fu_461_p2, sum_14_fu_488_p2, sum_15_fu_515_p2, sum_16_fu_542_p2, ap_condition_515)
    begin
        if ((ap_const_boolean_1 = ap_condition_515)) then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                output_r_TDATA <= sum_16_fu_542_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
                output_r_TDATA <= sum_15_fu_515_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                output_r_TDATA <= sum_14_fu_488_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
                output_r_TDATA <= sum_13_fu_461_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                output_r_TDATA <= sum_12_fu_434_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state4)) then 
                output_r_TDATA <= sum_fu_406_p2;
            else 
                output_r_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            output_r_TDATA <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    output_r_TDATA_blk_n_assign_proc : process(output_r_TREADY, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, icmp_ln28_reg_899)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            output_r_TDATA_blk_n <= output_r_TREADY;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    output_r_TVALID_assign_proc : process(image_r_TVALID, output_r_TREADY, ap_CS_fsm_state4, ap_CS_fsm_state5, ap_CS_fsm_state6, ap_CS_fsm_state7, ap_CS_fsm_state8, ap_CS_fsm_state9, icmp_ln28_reg_899, ap_block_state9_io, ap_block_state4_io, ap_block_state5_io, ap_block_state6_io, ap_block_state7_io, ap_block_state8_io)
    begin
        if (((not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state8_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state7_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state7) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state6_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state6) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state5_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state5) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state4_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln28_reg_899 = ap_const_lv1_0)) or (not(((image_r_TVALID = ap_const_logic_0) or (ap_const_boolean_1 = ap_block_state9_io) or ((output_r_TREADY = ap_const_logic_0) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state9) and (icmp_ln28_reg_899 = ap_const_lv1_0)))) then 
            output_r_TVALID <= ap_const_logic_1;
        else 
            output_r_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    sum_12_fu_434_p2 <= std_logic_vector(unsigned(add_ln65_8_fu_429_p2) + unsigned(add_ln65_6_fu_419_p2));
    sum_13_fu_461_p2 <= std_logic_vector(unsigned(add_ln65_13_fu_456_p2) + unsigned(add_ln65_11_fu_447_p2));
    sum_14_fu_488_p2 <= std_logic_vector(unsigned(add_ln65_18_fu_483_p2) + unsigned(add_ln65_16_fu_474_p2));
    sum_15_fu_515_p2 <= std_logic_vector(unsigned(add_ln65_23_fu_510_p2) + unsigned(add_ln65_21_fu_501_p2));
    sum_16_fu_542_p2 <= std_logic_vector(unsigned(add_ln65_28_fu_537_p2) + unsigned(add_ln65_26_fu_528_p2));
    sum_fu_406_p2 <= std_logic_vector(unsigned(add_ln65_3_fu_401_p2) + unsigned(add_ln65_1_fu_391_p2));
    tmp_8_fu_369_p4 <= i_fu_76(3 downto 1);
end behav;
